# Generated by Django 5.0.7 on 2024-07-27 09:15

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="",
                        help_text="タスクのタイトルを入力してください",
                        max_length=256,
                        verbose_name="タイトル",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="タスクの詳細を入力してください",
                        verbose_name="内容",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        default=datetime.datetime(
                            2024, 8, 1, 9, 15, 29, 316931, tzinfo=datetime.timezone.utc
                        ),
                        help_text="デフォルトでは5日後が設定されています",
                        verbose_name="期限",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="完了したらTrueにしてください",
                        verbose_name="完了",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="作成日時", verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="更新日時", verbose_name="更新日時"
                    ),
                ),
            ],
        ),
    ]
